/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScrollVideoRouteImport } from './routes/scroll-video'
import { Route as CategoriaAcessoriosRouteImport } from './routes/categoria/acessorios'
import { Route as CategoriaCalcasRouteImport } from './routes/categoria/calcas'
import { Route as CategoriaCamisetasRouteImport } from './routes/categoria/camisetas'
import { Route as CategoriaDestaqueRouteImport } from './routes/categoria/destaque'
import { Route as CategoriaHeadwearRouteImport } from './routes/categoria/headwear'
import { Route as CategoriaHoodiesRouteImport } from './routes/categoria/hoodies'
import { Route as CategoriaJaquetasRouteImport } from './routes/categoria/jaquetas'
import { Route as CategoriaShortsRouteImport } from './routes/categoria/shorts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollVideoRoute = ScrollVideoRouteImport.update({
  id: '/scroll-video',
  path: '/scroll-video',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaAcessoriosRoute = CategoriaAcessoriosRouteImport.update({
  id: '/categoria/acessorios',
  path: '/categoria/acessorios',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaCalcasRoute = CategoriaCalcasRouteImport.update({
  id: '/categoria/calcas',
  path: '/categoria/calcas',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaCamisetasRoute = CategoriaCamisetasRouteImport.update({
  id: '/categoria/camisetas',
  path: '/categoria/camisetas',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaDestaqueRoute = CategoriaDestaqueRouteImport.update({
  id: '/categoria/destaque',
  path: '/categoria/destaque',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaHeadwearRoute = CategoriaHeadwearRouteImport.update({
  id: '/categoria/headwear',
  path: '/categoria/headwear',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaHoodiesRoute = CategoriaHoodiesRouteImport.update({
  id: '/categoria/hoodies',
  path: '/categoria/hoodies',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaJaquetasRoute = CategoriaJaquetasRouteImport.update({
  id: '/categoria/jaquetas',
  path: '/categoria/jaquetas',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaShortsRoute = CategoriaShortsRouteImport.update({
  id: '/categoria/shorts',
  path: '/categoria/shorts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/profile': typeof ProfileRoute
  '/scroll-video': typeof ScrollVideoRoute
  '/categoria/acessorios': typeof CategoriaAcessoriosRoute
  '/categoria/calcas': typeof CategoriaCalcasRoute
  '/categoria/camisetas': typeof CategoriaCamisetasRoute
  '/categoria/destaque': typeof CategoriaDestaqueRoute
  '/categoria/headwear': typeof CategoriaHeadwearRoute
  '/categoria/hoodies': typeof CategoriaHoodiesRoute
  '/categoria/jaquetas': typeof CategoriaJaquetasRoute
  '/categoria/shorts': typeof CategoriaShortsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/profile': typeof ProfileRoute
  '/scroll-video': typeof ScrollVideoRoute
  '/categoria/acessorios': typeof CategoriaAcessoriosRoute
  '/categoria/calcas': typeof CategoriaCalcasRoute
  '/categoria/camisetas': typeof CategoriaCamisetasRoute
  '/categoria/destaque': typeof CategoriaDestaqueRoute
  '/categoria/headwear': typeof CategoriaHeadwearRoute
  '/categoria/hoodies': typeof CategoriaHoodiesRoute
  '/categoria/jaquetas': typeof CategoriaJaquetasRoute
  '/categoria/shorts': typeof CategoriaShortsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/profile': typeof ProfileRoute
  '/scroll-video': typeof ScrollVideoRoute
  '/categoria/acessorios': typeof CategoriaAcessoriosRoute
  '/categoria/calcas': typeof CategoriaCalcasRoute
  '/categoria/camisetas': typeof CategoriaCamisetasRoute
  '/categoria/destaque': typeof CategoriaDestaqueRoute
  '/categoria/headwear': typeof CategoriaHeadwearRoute
  '/categoria/hoodies': typeof CategoriaHoodiesRoute
  '/categoria/jaquetas': typeof CategoriaJaquetasRoute
  '/categoria/shorts': typeof CategoriaShortsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/profile'
    | '/scroll-video'
    | '/categoria/acessorios'
    | '/categoria/calcas'
    | '/categoria/camisetas'
    | '/categoria/destaque'
    | '/categoria/headwear'
    | '/categoria/hoodies'
    | '/categoria/jaquetas'
    | '/categoria/shorts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/profile'
    | '/scroll-video'
    | '/categoria/acessorios'
    | '/categoria/calcas'
    | '/categoria/camisetas'
    | '/categoria/destaque'
    | '/categoria/headwear'
    | '/categoria/hoodies'
    | '/categoria/jaquetas'
    | '/categoria/shorts'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/profile'
    | '/scroll-video'
    | '/categoria/acessorios'
    | '/categoria/calcas'
    | '/categoria/camisetas'
    | '/categoria/destaque'
    | '/categoria/headwear'
    | '/categoria/hoodies'
    | '/categoria/jaquetas'
    | '/categoria/shorts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ProfileRoute: typeof ProfileRoute
  ScrollVideoRoute: typeof ScrollVideoRoute
  CategoriaAcessoriosRoute: typeof CategoriaAcessoriosRoute
  CategoriaCalcasRoute: typeof CategoriaCalcasRoute
  CategoriaCamisetasRoute: typeof CategoriaCamisetasRoute
  CategoriaDestaqueRoute: typeof CategoriaDestaqueRoute
  CategoriaHeadwearRoute: typeof CategoriaHeadwearRoute
  CategoriaHoodiesRoute: typeof CategoriaHoodiesRoute
  CategoriaJaquetasRoute: typeof CategoriaJaquetasRoute
  CategoriaShortsRoute: typeof CategoriaShortsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scroll-video': {
      id: '/scroll-video'
      path: '/scroll-video'
      fullPath: '/scroll-video'
      preLoaderRoute: typeof ScrollVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/acessorios': {
      id: '/categoria/acessorios'
      path: '/categoria/acessorios'
      fullPath: '/categoria/acessorios'
      preLoaderRoute: typeof CategoriaAcessoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/calcas': {
      id: '/categoria/calcas'
      path: '/categoria/calcas'
      fullPath: '/categoria/calcas'
      preLoaderRoute: typeof CategoriaCalcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/camisetas': {
      id: '/categoria/camisetas'
      path: '/categoria/camisetas'
      fullPath: '/categoria/camisetas'
      preLoaderRoute: typeof CategoriaCamisetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/destaque': {
      id: '/categoria/destaque'
      path: '/categoria/destaque'
      fullPath: '/categoria/destaque'
      preLoaderRoute: typeof CategoriaDestaqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/headwear': {
      id: '/categoria/headwear'
      path: '/categoria/headwear'
      fullPath: '/categoria/headwear'
      preLoaderRoute: typeof CategoriaHeadwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/hoodies': {
      id: '/categoria/hoodies'
      path: '/categoria/hoodies'
      fullPath: '/categoria/hoodies'
      preLoaderRoute: typeof CategoriaHoodiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/jaquetas': {
      id: '/categoria/jaquetas'
      path: '/categoria/jaquetas'
      fullPath: '/categoria/jaquetas'
      preLoaderRoute: typeof CategoriaJaquetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/shorts': {
      id: '/categoria/shorts'
      path: '/categoria/shorts'
      fullPath: '/categoria/shorts'
      preLoaderRoute: typeof CategoriaShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ProfileRoute: ProfileRoute,
  ScrollVideoRoute: ScrollVideoRoute,
  CategoriaAcessoriosRoute: CategoriaAcessoriosRoute,
  CategoriaCalcasRoute: CategoriaCalcasRoute,
  CategoriaCamisetasRoute: CategoriaCamisetasRoute,
  CategoriaDestaqueRoute: CategoriaDestaqueRoute,
  CategoriaHeadwearRoute: CategoriaHeadwearRoute,
  CategoriaHoodiesRoute: CategoriaHoodiesRoute,
  CategoriaJaquetasRoute: CategoriaJaquetasRoute,
  CategoriaShortsRoute: CategoriaShortsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
